### ISSUE TITLE
Testing v3.1.0-rc7.2

### ISSUE THREAD

**Issue by cevap** [cevap/ion#106]
## Testing v3.1.0-rc7.2

[![PreRelease v3.1.00-rc7.2](https://img.shields.io/github/downloads/cevap/ion/v3.1.00-rc7.2/total.svg)](https://github.com/cevap/ion/releases/v3.1.00-rc7.2)

_Originally posted by @cevap in https://github.com/cevap/ion/issue_comments#issuecomment-449508722_

### Tests:
- [ ] https://github.com/cevap/ion/issues/107 - Test all rpccommands
- [ ] https://github.com/cevap/ion/issues/108 - Test snapcraft build: i386
- [ ] https://github.com/cevap/ion/issues/109 - Test snapcraft build: amd64
- [ ] https://github.com/cevap/ion/issues/110 - Test snapcraft build: armhf
- [ ] https://github.com/cevap/ion/issues/111 - Test snapcraft build: arm64
- [ ] https://github.com/cevap/ion/issues/112 - Test snapcraft build: ppc64el
- [ ] https://github.com/cevap/ion/issues/113 - Test snapcraft build: s390x
- [ ] https://github.com/cevap/ion/issues/114 - Test ion-tx
- [ ] https://github.com/cevap/ion/issues/115 - Test ion-cli
- [ ] https://github.com/cevap/ion/issues/116 - Test daemon
- [ ] https://github.com/cevap/ion/issues/117 - Test QT GUI, tools, menu, keyboard, mouse, ...
- [ ] https://github.com/cevap/ion/issues/119 - Test gitian build: MacOS Mojave (macOS v10.14.1)
- [ ] https://github.com/cevap/ion/issues/118 - Test gitian build: MacOS High Sierra (macOS 10.13.4/macOS 10.13.5/macOS 10.13.6)
- [ ] https://github.com/cevap/ion/issues/120 - Test gitian build: MacOS Sierra (macOS v10.12.0/macOS v10.12.4)
- [ ] https://github.com/cevap/ion/issues/121 - Test gitian build: MacOS El Capitan (OS X v10.11.0/OS X v10.11.6)
- [ ] https://github.com/cevap/ion/issues/122 - Test gitian build: MacOS Yosemite (OS X v10.10.0/OS X v10.10.5)
- [ ] https://github.com/cevap/ion/issues/123 - Test gitian build: MacOS Mavericks (OS X v10.9.0/OS X v10.9.5)
- [ ] https://github.com/cevap/ion/issues/124 - Test gitian build: Windows (XP/VISTA/7/10/Server)

**Comment by cevap** [comment]
**Community is not active**, untested stays untested, and with that issue closed. If somebody tests and has any issues, feel free to reopne or create new issue.
